ALTER TABLE `categories`
ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `updated_at` DATETIME on update CURRENT_TIMESTAMP NULL DEFAULT NULL AFTER `created_at`,
ADD `deleted_at` DATETIME NULL DEFAULT NULL AFTER `updated_at`;

ALTER TABLE `produits`
ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `updated_at` DATETIME on update CURRENT_TIMESTAMP NULL DEFAULT NULL AFTER `created_at`,
ADD `deleted_at` DATETIME NULL DEFAULT NULL AFTER `updated_at`;

ALTER TABLE `couleurs`
ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `updated_at` DATETIME on update CURRENT_TIMESTAMP NULL DEFAULT NULL AFTER `created_at`,
ADD `deleted_at` DATETIME NULL DEFAULT NULL AFTER `updated_at`;